  
SELECT
`COLUMNS`.`TABLE_CATALOG`,
`COLUMNS`.`TABLE_SCHEMA`,
`COLUMNS`.`TABLE_NAME`,
`COLUMNS`.`COLUMN_NAME`,
`COLUMNS`.`ORDINAL_POSITION`,
`COLUMNS`.`COLUMN_DEFAULT`,
`COLUMNS`.`IS_NULLABLE`,
`COLUMNS`.`DATA_TYPE`,
`COLUMNS`.`CHARACTER_MAXIMUM_LENGTH`,
`COLUMNS`.`CHARACTER_OCTET_LENGTH`,
`COLUMNS`.`NUMERIC_PRECISION`,
`COLUMNS`.`NUMERIC_SCALE`,
`COLUMNS`.`CHARACTER_SET_NAME`,
`COLUMNS`.`COLLATION_NAME`,
`COLUMNS`.`COLUMN_TYPE`,
`COLUMNS`.`COLUMN_KEY`,
`COLUMNS`.`EXTRA`,
`COLUMNS`.`PRIVILEGES`,
`COLUMNS`.`COLUMN_COMMENT`
FROM `INFORMATION_SCHEMA`.`COLUMNS`
where TABLE_SCHEMA = 'UDA_Repertoire_dbo'
and COLUMN_NAME like '%alias%'
;


 