BEGIN TRAN

SELECT t.name as nomTable

,ORDINAL_POSITION, COLUMN_NAME
,DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
,COLUMN_DEFAULT  , IS_NULLABLE 
 
FROM sys.tables AS t 

INNER JOIN  INFORMATION_SCHEMA.COLUMNS as ic
	on t.name = ic.TABLE_NAME 
	 
ORDER BY t.name, ORDINAL_POSITION 



SELECT TABLE_NAME, CONSTRAINT_NAME 
FROM INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE
ORDER BY TABLE_NAME, CONSTRAINT_NAME 

SELECT name, type_desc, is_unique, is_primary_key,*
FROM sys.indexes 


ROLLBACK