 

USE MASTER
GO

ALTER DATABASE Sigart_ASB
MODIFY FILE
(NAME = SIGAR_Data, NEWNAME='SIGART_Dat')
GO

ALTER DATABASE Sigart_ASB
MODIFY FILE
(NAME = SIGAR_Log, NEWNAME='SIGART_Log')
GO

ALTER DATABASE Sigart_ASB
MODIFY FILE
(NAME = SIGAR_BLOB, NEWNAME='SIGART_BLOB')
GO


CREATE DATABASE Sigart_ASB ON 
( FILENAME = N'E:\BD_Sigart_Test\SIGART_ASB.mdf' ),
( FILENAME = N'E:\BD_Sigart_Test\SIGART_ASB_2.ldf' ),
( FILENAME = N'E:\BD_Sigart_Test\SIGART_ASB_1.ndf' )
FOR ATTACH
GO
